movie_project/movie_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_project/users/urls.py
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.CustomRegisterView.as_view(), name='register'),
    path("logout", views.logout, name="logout"),
    path("watchlist/", views.MyWatchlistView.as_view(), name='watchlist'),
    path('profile/<int:pk>', views.ProfileDetailView.as_view(), name="profile"),
    path('follow/<str:model_name>/<int:object_id>/', views.follow_content, name='follow_content'),
    path('create_list', views.CreateListView.as_view(), name='create-list'),
    path('lists/<int:pk>', views.CustomListDetailView.as_view(), name='list-detail'),
    path('add_to_watched_movies/<int:id>/', views.add_to_watched_movies, name='add_to_watched_movies'),
    path('add_to_favorites/<str:model_name>/<int:object_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('add_to_list/<int:custom_list_id>/<int:movie_id>/', views.add_to_list, name="add_to_list"),
]

htmx_urlpatterns = [
    path('check_username/', views.check_username, name="check_username"),
    path('edit_profile_image', views.edit_profile_image, name="edit_profile_image"),
    path('edit_custom_list/<int:id>/', views.edit_custom_list, name="edit_custom_list"),
]

urlpatterns += htmx_urlpatterns

movie_project/users/models.py
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    watchlist = models.ForeignKey('Watchlist' ,related_name="profiles", on_delete=models.CASCADE)
    following = models.ManyToManyField('self', symmetrical=False, related_name='followers', blank=True)
    watched_movies = models.ManyToManyField('movies.Movie', blank=True, related_name='watched_by')
    image = models.ImageField(upload_to="media", default="media/default.jfif")

    def __str__(self):
        return self.user.username
    
class Watchlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    movies = models.ManyToManyField('movies.Movie', related_name="watchlists", null=True, blank=True)

    def __str__(self):
        return  f"{self.user}'s watchlist"
    
class Follow(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="follows")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f'{self.profile.user.username} follows {self.content_object}'
    
class CustomList(models.Model):
    PRIVACY_CHOICES = [
        ('friends', 'Friends'),
        ('everyone', 'Everyone'),
        ('only_me', 'Only Me')
    ]

    name = models.TextField()
    description = models.TextField(blank=True)
    profile = models.ForeignKey(Profile, related_name="lists", on_delete=models.CASCADE)
    movies = models.ManyToManyField('movies.Movie', related_name='lists', blank=True)
    privacy = models.TextField(choices=PRIVACY_CHOICES, default='everyone')
    ranked_list = models.BooleanField(default=False)
    created_on = models.DateTimeField(default=timezone.now, editable=False)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name
    

class Favorite(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='favorites')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE) # used content_type instead so it can apply to TV series model as well
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"{self.profile} added {self.content_object} to favorites"

movie_project/users/forms.py
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django import forms
from movies.models import User
from users.models import CustomList, Profile


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class CustomListForm(forms.ModelForm):
    class Meta:
        model = CustomList
        fields = ["name", "movies", "description", "privacy", "ranked_list"]
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control', 
                'id': 'id_name'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'id': 'id_description'
            }),
            'movies': forms.SelectMultiple(attrs={
                'class': 'form-control', 
                'id': 'id_movies' 
            }),
        }

class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = Profile

        fields = ['image']

movie_project/users/views.py
import random
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login, logout as auth_logout
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views import View
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from movies.forms import MovieSortForm, SearchForm
from movies.utils import available_actors, available_award_categories, get_available_genres, filter_queryset, sort, toggle_upcoming
from users.models import CustomList, Favorite, Follow, Profile, Watchlist
from .forms import CustomUserCreationForm, CustomListForm, ProfileImageForm
from django.views.generic import ListView, DetailView, CreateView
from django.db.models import Q, Avg
from movies.models import Award, Genre, Movie, MovieImage, Review, User
from django.template.loader import render_to_string
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
class CustomLoginView(LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    model = Movie # only for getting random image 

    def get_success_url(self) -> str:
        return reverse_lazy('index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie_images = MovieImage.objects.all()
                
        context.update({
            'movie_images': movie_images,
            'random_image': random.choice(movie_images)
        })

        return context
    
class CustomRegisterView(CreateView):
    template_name = 'users/register.html'
    redirect_authenticated_user = True
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie_images = MovieImage.objects.all()

        context.update({
            'movie_images': movie_images,
            'random_image': random.choice(movie_images)
        })
        return context
        
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect("/")

class MyWatchlistView(View):
    model = Watchlist
    template_name = 'users/watchlist.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        watchlist = Watchlist.objects.get(user=user)
        watchlist_movies = watchlist.movies.all().order_by('title')

        view_mode = request.GET.get('view', 'list')

        # Search functionality
        search_form = SearchForm(request.GET or None)
        if search_form.is_valid():
            query = search_form.cleaned_data.get('query')
            watchlist_movies = watchlist_movies.filter(title__icontains=query)

        # Calculate available genres and award categories with winners before applying filters
        genres_with_movies = get_available_genres(watchlist_movies)
        award_categories_with_winners = available_award_categories(watchlist_movies)
        actors_with_movies = available_actors(watchlist_movies)

        # Sorting logic
        sort_form = MovieSortForm(request.GET or None)
        if sort_form.is_valid():
            sort_by = sort_form.cleaned_data.get('sort_by')
            watchlist_movies = sort(watchlist_movies, sort_by)

        # Filtering logic
        selected_genres = request.GET.getlist('genre')
        selected_award_categories = request.GET.getlist('award_category')
        selected_actors = request.GET.getlist('actor')

        filters = Q()

        # Add genre filters 
        if selected_genres:
            genre_q = Q()
            for genre_name in selected_genres:
                genre_q |= Q(genres__name=genre_name)
            filters |= genre_q

        # Add award category filters 
        if selected_award_categories:
            award_q = Q()
            for award_category in selected_award_categories:
                award_q |= Q(awards__category=award_category, awards__winner=True)
            filters |= award_q

        # Add actor filters 
        if selected_actors:
            actor_q = Q()
            for actor in selected_actors:
                actor_q |= Q(actors__name=actor)
            filters |= actor_q

        # Apply the combined filters to the queryset
        if filters:
            watchlist_movies = watchlist_movies.filter(filters).distinct()

        # Get distinct award categories where the movie is a winner
        award_categories = Award.objects.filter(winner=True).values_list('category', flat=True).distinct()

        show_layout_buttons = True

        context = {
            'watchlist_movies': watchlist_movies,
            'search_form': search_form, 
            'sort_form': sort_form,
            'available_genres': genres_with_movies,  
            'award_categories_with_winners': award_categories_with_winners,
            'selected_genres': selected_genres,
            'award_categories': award_categories,
            'selected_award_categories': selected_award_categories,
            'actors_with_movies': actors_with_movies,
            'selected_actors': selected_actors,
            'upcoming': request.GET.get('upcoming', 'off'),
            'view_mode': view_mode,
            'show_layout_buttons': show_layout_buttons,
        }
        return render(request, self.template_name, context)
    

class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'users/profile.html'
    context_object_name = 'profile'

    def get(self, request, *args, **kwargs):
        profile = self.get_object()
        following_count = Follow.objects.filter(profile=profile).count() + profile.following.count()
        followers_count = Profile.objects.filter(following=profile).count()
        review_count = Review.objects.filter(user=profile.user).count()

        form = ProfileImageForm(instance=profile)

        context = {
            'profile': profile,
            'following_count': following_count,
            'followers_count': followers_count,
            'review_count': review_count,
            'form': form
        }

        return render(request, self.template_name, context)

@login_required(login_url='login')
def follow_content(request, model_name, object_id):
    content_type = get_object_or_404(ContentType, model=model_name)

    profile = get_object_or_404(Profile, user=request.user)

    follow = Follow.objects.filter(profile=profile, content_type=content_type, object_id=object_id)
    is_followed = follow.exists()

    if is_followed:
        follow.delete()
        followed = False
    else:
        follow = Follow.objects.create(profile=profile, content_type=content_type, object_id=object_id)
        followed = True

    return JsonResponse({
        'followed': followed
    })


class CreateListView(CreateView):
    model = CustomList
    template_name = 'users/create-list.html'
    form_class = CustomListForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            movies = form.cleaned_data.get('movies')
            privacy = request.POST.get('privacy')
            ranked_list = form.cleaned_data['ranked_list']
            profile = Profile.objects.get(user=request.user)

            user_list = CustomList.objects.create(name=name, 
                                                description=description, 
                                                privacy=privacy, 
                                                ranked_list=ranked_list, 
                                                profile=profile)

            user_list.movies.set(movies)

            return HttpResponseRedirect(reverse('list-detail', args=[user_list.pk]))
        
        return redirect('index')

    def get(self, request, *args, **kwargs):

        context = {
            'form': self.form_class(),
            'movies': Movie.objects.all()
        }

        return render(request, self.template_name, context)
    
class CustomListDetailView(DetailView):
    model = CustomList
    template_name = 'users/list-detail.html'
    context_object_name = 'list'

    def get(self, request, **kwargs):
        custom_list = self.get_object()
        form = CustomListForm(instance=custom_list)
        custom_list_movies = custom_list.movies.all()

        # Only increment view count if it's the first time this request is being made (not a view_mode toggle)
        if 'view' not in request.GET:
            custom_list.views += 1
            custom_list.save()

        watched_movies_count = custom_list_movies.filter(id__in=request.user.profile.watched_movies.values('id')).count()

        genres_with_movies = get_available_genres(custom_list_movies)
        award_categories_with_winners = available_award_categories(custom_list_movies)
        actors_with_movies = available_actors(custom_list_movies)

        view_mode = request.GET.get('view', 'list')
        show_layout_buttons = True

        search_form = SearchForm(request.GET or None)
        if search_form.is_valid():
            query = search_form.cleaned_data.get('query')
            custom_list_movies = custom_list_movies.filter(title__icontains=query)

        sort_form = MovieSortForm(request.GET or None)
        if sort_form.is_valid():
            sort_by = sort_form.cleaned_data.get('sort_by')

movie_project/users/templates/users/create-list.html
{% extends 'movies/layout.html' %}

{% block title %} MovieVerse: New List {% endblock %}

{% block body %}
    <form class="custom-list-form" method="POST">
        {% csrf_token %}
        <div class="header">
            <h1>New List</h1>
            <p>Start your custom movie library.</p>
        </div>
        <div class="line"></div>

        <div class="wrapper">
            <div>
                <h4>Name</h4>
                {{ form.name }}

                <!-- Privacy -->
                <h4>Who can see?</h4>
                <div id="id_privacy">
                    <button type=button id="privacy-btn">
                        <input type="radio" name="privacy" value="friends" class="form-check-input" id="id_privacy_0">
                        <i class="fa-solid fa-user-group"></i>
                        <label for="id_privacy_0">Friends</label>
                    </button>
                    <button type=button id="privacy-btn">
                        <input type="radio" name="privacy" value="everyone" class="form-check-input" id="id_privacy_1">
                        <i class="fa-solid fa-globe"></i>
                        <label for="id_privacy_1">Everyone</label>
                    </button>
                    <button type=button id="privacy-btn">
                        <input type="radio" name="privacy" value="only_me" class="form-check-input" id="id_privacy_2">
                        <i class="fa-solid fa-user"></i>
                        <label for="id_privacy_2">Only Me</label>
                    </button>
                </div>

                <!-- Movies -->
                <div>
                    <h4>Select Movies</h4>
                    {{ form.movies }}
                </div>
                
                
                <!-- Ranked List or Not-->
                <div style="display: flex; align-items: center; gap: 0.5rem; margin-top: 1rem;">
                    <input type="checkbox" name="ranked_list" id="id_ranked_list">
                    <label for="id_ranked_list" id="ranked_list-label">Ranked List</label>
                    <p>(Show position for each film)</p>
                </div>

            </div>

            <div>
                <h4>Description</h4>
                {{ form.description }}
            </div>
        </div>
        <div>
            <div class="form-actions">
                <button type="reset">Reset</button>
                <button type="submit">Save</button>
            </div>
        </div>
    </form>
{% endblock %}

movie_project/users/templates/users/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Users {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'users/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="container">
        <div class="content-wrapper">
            {% block body %}
            {% endblock %}
        </div>
    </div>    
</div>
</body>
<script src="https://unpkg.com/htmx.org@2.0.4"></script>
</html>

movie_project/users/templates/users/list-detail.html
{% extends 'movies/layout.html' %}

{% block title %} {{ custom_list.name }} {% endblock %}

{% block body %}

<div class="form-modal">
    {% include 'users/partials/list-form.html' %}
</div>

<section class="list-section">

    <header class="header" id="list-header">

        <div>
            <div class="wrapper">

                <h1 id="list-name">{{ custom_list.name }}</h1>
                {% if request.user == custom_list.profile.user %}
                    <i class="fa-regular fa-pen-to-square" id="edit-list-btn"></i>
                {% endif %}

            </div>
            <h3 style="margin-top: 10px;">By <a href="{% url 'profile' custom_list.profile.user.pk %}">{{ custom_list.profile.user }}</a> • Created on {{ custom_list.created_on|date:"F d Y" }}</h3>
        
        </div>

        <div style="display: flex; flex-direction: column; gap: 1rem;">
            <div class="wrapper" id="list-stat-wrapper">
                <div class="list-statistic">
                    <i class="fa-solid fa-eye"></i>
                    <p>{{ custom_list.views }} views</p>
                </div>
                <div class="list-statistic">
                    <i class="fa-solid fa-film"></i>
                    <p>{{ custom_list.movies.count }} Titles</p>
                </div>
                <div class="list-statistic">
                    {% if custom_list.privacy == 'everyone' %}
                        <i class="fa-solid fa-globe"></i>
                    {% elif custom_list.privacy == 'friends' %}
                        <i class="fa-solid fa-user-group"></i>
                    {% elif custom_list.privacy == 'only_me' %}
                        <i class="fa-solid fa-lock"></i>
                    {% endif %}
                    <p>{{ custom_list.get_privacy_display }}</p>
                </div>
                <div>
                    <i class="fa-solid fa-share-nodes" id="share-btn"></i>
                </div>
            </div>
            <p id="watched-movies-count">You've watched {{ watched_movies_count }} out of {{ custom_list_movies.count }}</p>
        </div>
        
    </header>
    
    <main class="list-container">

        {% include 'users/partials/filter-sidebar.html' %}
    
        <div class="content" id="list-content" hx-swap-oob="true">

            {% if custom_list.description %}
                <h3>Description</h3>
                <p id="list-desc">{{ custom_list.description }}</p>
            {% else %}
                <p id="list-desc">No description yet.</p>
            {% endif %}

            <div class="line"></div>

            {% include 'users/partials/form-wrapper.html' %} 
    
            <ol>
                {% for movie in custom_list_movies %}
                    {% if view_mode == 'grid' %}
                        <li>
                            {% include 'movies/partials/card.html' %}
                        </li>
                    {% else %}
                        {% include 'movies/partials/movie-list-item.html' %}
                    {% endif %}
                {% endfor %}
            </ol>

        </div>
    </main>
</section>
{% endblock %}

movie_project/users/templates/users/login.html
{% extends 'users/layout.html' %}

{% block title %} Login {% endblock %}

{% block body %}
<div class="image">
    <img src="{{ random_image.image.url }}" alt="Movie Image">
    <div class="logo">
        <a href="{% url 'index' %}">MovieVerse</a>
    </div>
    <div class="overlay">
        <p>Your Ultimate Movie Companion</p>
    </div>
</div>
<div class="form-list">
    <div class="header">
        <h1>Welcome Back</h1>
        <p>Sign in to access your account.</p>
    </div>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <input type="text" name="username" placeholder="Username" id="id_username" required>
            <input type="password" name="password" placeholder="Password" id="id_password" required>
        </div>
        <button type="submit">Sign In</button>
        <div class="social-signin-divider">
            <div class="line"></div>
            <p>or sign in with</p>
            <div class="line"></div>
        </div>
        <div class="social-login-buttons">
            <i class="fa-brands fa-google"></i>
            <i class="fa-brands fa-facebook-f"></i>
            <i class="fa-brands fa-apple"></i>
            <i class="fa-brands fa-microsoft"></i>
        </div>
        <div class="form-footer-link">
            <p>Don't have an account yet?</p>
            <a href="{% url 'register' %}">Register</a>
        </div>
        {% if form.errors %}
            <div class="error-messages">
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </form>
</div>
{% endblock %}

movie_project/users/templates/users/register.html
{% extends 'users/layout.html' %}

{% block title %} Register {% endblock %}

{% block body %}
<div class="form-list">
    <div class="header">
        <h1>Create an Account</h1>
        <p>Register to join our community.</p>
    </div>
    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <input type="text" name="username" placeholder="Username" id="id_username" required
            hx-post="{% url 'check_username' %}"
            hx-trigger="keyup changed delay:0.5s"
            hx-target="#username-error"
            >
            <div id="username-error"></div>
            <input type="email" name="email" placeholder="Email" id="id_email" required>
            <input type="password" name="password1" placeholder="Password" minlength="8" id="id_password1" required>
            <input type="password" name="password2" placeholder="Confirm Password" minlength="8" id="id_password2" required>
        </div>
        <button type="submit">Register</button>
        <div class="social-signin-divider">
            <div class="line"></div>
            <p>or register with</p>
            <div class="line"></div>
        </div>
        <div class="social-login-buttons">
            <i class="fa-brands fa-google"></i>
            <i class="fa-brands fa-facebook-f"></i>
            <i class="fa-brands fa-apple"></i>
            <i class="fa-brands fa-microsoft"></i>
        </div>
        <div class="form-footer-link">
            <p>Already have an account?</p>
            <a href="{% url 'login' %}">Sign In</a>
        </div>
        {% if form.errors %}
            <div class="error-messages">
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </form>
</div>
<div class="image">
    <img src="{{ random_image.image.url }}" alt="Movie Image">
    <div class="logo">
        <a href="{% url 'index' %}">MovieVerse</a>
    </div>
    <div class="overlay">
        <p>Your Ultimate Movie Companion</p>
    </div>
</div>
{% endblock %}

movie_project/users/templates/users/watchlist.html
{% extends 'movies/layout.html' %}

{% block title %} {{ user }}'s Watchlist {% endblock %}

{% block body %}
<section class="list-section">
    <header class="header">
        <div>
            <h1>Watchlist</h1>
            <h3 style="margin-top: 10px;">Your Movie Picks, All in One Place.</h3>
        </div>
        <div>
            <h3>{{ watchlist_movies.count }} Titles</h3>
        </div>
    </header>

    

    <main class="list-container">

        {% include 'users/partials/filter-sidebar.html' %}
    
        <div class="content">
            
            {% include 'users/partials/form-wrapper.html' %} 
    
            <ol>
                {% for movie in watchlist_movies %}
                    {% if view_mode == 'grid' %}
                        <li class="skeleton">
                            {% include 'movies/partials/card.html' %}
                        </li>
                    {% else %}
                        {% include 'movies/partials/movie-list-item.html' %}
                    {% endif %}
                {% endfor %}
            </ol>

        </div>
    </main>
    
</section>
{% endblock %}